kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-flexblock-attacher
  labels:
    app: csi-flexblock-attacher
spec:
  #serviceName: "csi-flexblock-attacher"
  #replicas: 3
  selector:
    matchLabels:
      app: csi-flexblock-attacher
  template:
    metadata:
      labels:
        app: csi-flexblock-attacher
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-flexblockplugin
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-flexblock
            type: DirectoryOrCreate
          name: socket-dir
